import type { Metadata } from "next";
import { getBaselinePublic } from "@/lib/audit/baseline-store";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Audit Record Verification — AccessiScan",
  robots: { index: false, follow: false },
};

export default async function VerifyPage({ params }: { params: Promise<{ auditId: string }> }) {
  const { auditId } = await params;
  const record = await getBaselinePublic(auditId);

  const wrap: React.CSSProperties = {
    maxWidth: 640,
    margin: "48px auto",
    padding: "0 20px",
    fontFamily: "Inter, Arial, sans-serif",
    color: "#0f172a",
    lineHeight: 1.6,
  };

  if (!record) {
    return (
      <main style={wrap}>
        <h1 style={{ fontSize: 22 }}>Audit record not found</h1>
        <p style={{ color: "#64748b" }}>
          No audit baseline matches this identifier. Check the verification link in your report email.
        </p>
      </main>
    );
  }

  const row: React.CSSProperties = { padding: "10px 0", borderBottom: "1px solid #e2e8f0", fontSize: 14 };
  const label: React.CSSProperties = { color: "#64748b", fontSize: 12, textTransform: "uppercase", letterSpacing: 0.5 };

  return (
    <main style={wrap}>
      <div style={{ display: "inline-block", background: "#dcfce7", color: "#166534", fontWeight: 700, fontSize: 13, padding: "6px 14px", borderRadius: 999 }}>
        ✓ BASELINE ESTABLISHED
      </div>
      <h1 style={{ fontSize: 24, margin: "16px 0 4px" }}>WCAG Audit Record</h1>
      <p style={{ color: "#64748b", marginTop: 0 }}>Independent verification — AccessiScan</p>

      <div style={{ marginTop: 24, border: "1px solid #e2e8f0", borderRadius: 12, padding: "8px 20px" }}>
        <div style={row}>
          <div style={label}>Target URL</div>
          <div>{record.targetUrl}</div>
        </div>
        <div style={row}>
          <div style={label}>Scanned at (UTC)</div>
          <div>{record.scannedAt}</div>
        </div>
        <div style={row}>
          <div style={label}>Engine</div>
          <div>{record.engineVersion}</div>
        </div>
        <div style={{ ...row, borderBottom: "none" }}>
          <div style={label}>SHA-256 of findings</div>
          <div style={{ fontFamily: "ui-monospace, monospace", fontSize: 12, wordBreak: "break-all" }}>
            {record.violationsHash}
          </div>
        </div>
      </div>

      <p style={{ marginTop: 24, fontSize: 13, color: "#475569", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 8, padding: 14 }}>
        This page confirms that the audit file referenced by this hash was generated by AccessiScan on the date
        shown and has not been altered since. It does not confirm that the audited website meets WCAG 2.1 AA,
        satisfies ADA Title III, or is free from accessibility barriers. The hash is the SHA-256 of the
        canonicalized findings (sorted keys, UTF-8).
      </p>
    </main>
  );
}
